### ISSUE TITLE
MLJ 0.17 breaks `fit!` in tutorial 02

### ISSUE THREAD

**Issue by roland-KA** [ablaom/MLJTutorial.jl#24]
I've updated the Pluto notebook for tutorial 02 to MLJ 0.17 as well as all other packages to their most recent versions.

<details>
<summary>Version changes in detail</summary>

**Old versions**:
CSV = "~0.9.10"
DataFrames = "~1.2.2"
Distributions = "~0.25.28"
MLJ = "~0.16.11"
MLJFlux = "~0.2.5"
Plots = "~1.23.6"
PlutoUI = "~0.7.19"
Tables = "~1.6.0"
UrlDownload = "~1.0.0"

**New versions**:
CSV = "~0.9.11"
DataFrames = "~1.3.1"
Distributions = "~0.25.37"
MLJ = "~0.17.0"
MLJFlux = "~0.2.6"
Plots = "~1.25.4"
PlutoUI = "~0.7.27"
Tables = "~1.6.1"
UrlDownload = "~1.0.0"
</details>

This breaks the first `fit!` statement in the tutorial (in 'Step 3'):

`fit!(mach, rows=train, verbosity=2)`

It comes up with the following error message:

```
UndefVarError: scitype not defined

reformat(::DataFrames.DataFrame)@core.jl:167
collate(::MLJFlux.NeuralNetworkClassifier{MLJFlux.Short, typeof(NNlib.softmax), Flux.Optimise.ADAM, typeof(Flux.Losses.crossentropy)}, ::DataFrames.DataFrame, ::CategoricalArrays.CategoricalVector{String, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Union{}})@core.jl:247
fit(::MLJFlux.NeuralNetworkClassifier{MLJFlux.Short, typeof(NNlib.softmax), Flux.Optimise.ADAM, typeof(Flux.Losses.crossentropy)}, ::Int64, ::DataFrames.DataFrame, ::CategoricalArrays.CategoricalVector{String, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Union{}})@mlj_model_interface.jl:56
var"#fit_only!#53"(::Vector{Int64}, ::Int64, ::Bool, ::typeof(MLJBase.fit_only!), ::MLJBase.Machine{MLJFlux.NeuralNetworkClassifier{MLJFlux.Short, typeof(NNlib.softmax), Flux.Optimise.ADAM, typeof(Flux.Losses.crossentropy)}, true})@machines.jl:592
#fit!#58@machines.jl:659[inlined]
top-level scope@Local: 1[inlined]
```

I can't relate this error to any of the changes coming with the new releases.

**Comment by ablaom** [comment]
Thanks for reporting!

I figure [this bug fix](https://github.com/JuliaAI/MLJModelInterface.jl/pull/130) should address the issue.

**Comment by roland-KA** [comment]
Thanks for the fast response!

As I've understood from your comments 
> A. We have backwards compatibility: All MLJBase 0.18.* are compatible with the new MLJModelInteface 1.3.5.
> B. We yank MLJBase 0.18 and 0.18.1 (already released) from General, after the new patch MLJBase 0.18.2

there will be a new vers. 1.3.5 of _MLJModelInterface_ and a new vers. of 0.18.2 _MLJBase_ which include the bug fix? 

I've updated both packages in the notebook explicitly. But I'm getting as the most recent versions:
- MLJModelInterface 1.3.4
- MLJBase 0.19.1

So I'm a bit confused about which versions to use (especially _MLJModelInterface_ 1.3.5 isn't available yet) ... or is there another way to include the bug fix?

**Comment by ablaom** [comment]
Yeah sorry, there's a typo. It should read:

> B. We yank MLJBase 0.18 and 0.18.1 (already released) from General, after the new patch MLJBase 0.19.2

So you need to wait for MLJBase 0.19.2 (and MLJModelInterface 1.3.5). I expect these to be released within 24 hrs. Thanks for your patience.

cc @OkonSamuel

**Comment by roland-KA** [comment]
Oh, then I was just a bit too fast. Well, that's easy to solve 😊.

Then I'll try it, when the respective versions are available. 👍

**Comment by ablaom** [comment]
This should work now. Please confirm at your leisure by closing the issue.

**Comment by ablaom** [comment]
Hold on, there is still a remaining [issue](https://github.com/JuliaAI/MLJModels.jl/issues/423). We got the carpet to fit in one corner but ...

**Comment by roland-KA** [comment]
Ok, I see. Thanks for the information!

I have a more general question within this context: The call to `fit!` in tutorial 02 which caused the original error is (to my understanding) quite basic usage of MLJ. Why didn't the automated tests of MLJ detect this error? I.e. may it be useful to add some test case there?

**Comment by ablaom** [comment]
> I have a more general question within this context: The call to fit! in tutorial 02 which caused the original error is (to my understanding) quite basic usage of MLJ. Why didn't the automated tests of MLJ detect this error? I.e. may it be useful to add some test case there?

MLJ itself does almost no testing, as it just pulls in other packages and re-exports stuff. The error was that the low level package `MLJModelInterface` had a non-breaking release that stopped exporting a certain method (`scitype`). We had tested every "meta" MLJ package downstream, but do not currently test every model interface package - only that the models they provide can be *loaded* (these tests are part of MLJModels CI). Since the issue, we have tested all the model interface packages but only MLJFlux seems to have hit the problem, as you discovered. 

However, in light of the recent experience, we plan to create a new package to provide integration tests for the whole eco-system. (Since we have less control over 3rd party packages, which are not dependencies of MLJ, it seems to make sense to make this a separate package.) https://github.com/alan-turing-institute/MLJ.jl/issues/885

**Comment by roland-KA** [comment]
Thank you very much for the explanation! Now it's much clearer to me on what happened when the call to `fit` failed. ... and well, things are quite complex (more than I thought 🤓).

I think it's a really good idea to add integration tests. Since on the one hand you don't have control over the external models, but from an end user perspective "MLJ works" when the combination of of MLJ _and_ external models do their job well in concert.

**Comment by roland-KA** [comment]
The call to `fit!` works now.

But care has to be taken to `*using* ScientificTypes` and `*import* MLJModelInterface` so that the exported `scitype`s don't clash.
